In [1]:
import pandas as pd

In [2]:
# 1. Criação do DataFrame base simulando os meses da operação
dados = {
    'Mes': ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago'],
    'Entradas_GEREL': [2048, 2059, 1837, 1484, 1535, 1654, 2083, 2584],
    'Escalonados_GECRE': [589, 681, 656, 433, 574, 578, 637, 888],
    'Dias_Corridos': [31, 28, 31, 30, 31, 30, 31, 31]
}
display =dados = pd.DataFrame(dados)
dados

   Mes  Entradas_GEREL  Escalonados_GECRE  Dias_Corridos
0  Jan            2048                589             31
1  Fev            2059                681             28
2  Mar            1837                656             31
3  Abr            1484                433             30
4  Mai            1535                574             31
5  Jun            1654                578             30
6  Jul            2083                637             31
7  Ago            2584                888             31

In [10]:
df = pd.DataFrame(dados)
# Média, Mediana e Desvio Padrão
media = df['Entradas_GEREL'].mean()
mediama =df['Entradas_GEREL'].median()

np.float64(1910.5)

In [3]:
df = pd.DataFrame(dados)
media = df['Entradas_GEREL'].mean()
df

   Mes  Entradas_GEREL  Escalonados_GECRE  Dias_Corridos
0  Jan            2048                589             31
1  Fev            2059                681             28
2  Mar            1837                656             31
3  Abr            1484                433             30
4  Mai            1535                574             31
5  Jun            1654                578             30
6  Jul            2083                637             31
7  Ago            2584                888             31

In [9]:
df = pd.DataFrame(dados)
# Média, Mediana e Desvio Padrão
media = df['Entradas_GEREL'].mean()
mediana = df['Entradas_GEREL'].median()
desvio_padrao = df['Entradas_GEREL'].std()
print(f"Média: {media}")

Média: 1910.5

In [31]:
cv = (desvio_padrao / media) * 100
cv

np.float64(18.95933872301111)

In [32]:
# Alerta Exploratório de Tukey (IQR) para identificar os Outliers de Escalonamento
Q1 = df['Escalonados_GECRE'].quantile(0.25)
Q3 = df['Escalonados_GECRE'].quantile(0.75)
IQR = Q3 - Q1
limiar_superior = Q3 + 1.5 * IQR

In [33]:
df['Alerta_Sobrecarga'] = df['Escalonados_GECRE'] > limiar_superior
df

   Mes  Entradas_GEREL  Escalonados_GECRE  Dias_Corridos  Alerta_Sobrecarga
0  Jan            2048                589             31              False
1  Fev            2059                681             28              False
2  Mar            1837                656             31              False
3  Abr            1484                433             30              False
4  Mai            1535                574             31              False
5  Jun            1654                578             30              False
6  Jul            2083                637             31              False
7  Ago            2584                888             31               True

In [34]:
df['YTD_Entradas'] = df['Entradas_GEREL'].cumsum()
df

,Mes,Entradas_GEREL,Escalonados_GECRE,Dias_Corridos,Alerta_Sobrecarga,YTD_Entradas
0,Jan,2048,589,31,False,2048
1,Fev,2059,681,28,False,4107
2,Mar,1837,656,31,False,5944
3,Abr,1484,433,30,False,7428
4,Mai,1535,574,31,False,8963
5,Jun,1654,578,30,False,10617
6,Jul,2083,637,31,False,12700
7,Ago,2584,888,31,True,15284

In [35]:
df['MMA_3_Entradas'] = df['Entradas_GEREL'].rolling(window=3).mean()
df

,Mes,Entradas_GEREL,Escalonados_GECRE,Dias_Corridos,Alerta_Sobrecarga,YTD_Entradas,MMA_3_Entradas
0,Jan,2048,589,31,False,2048,NaN
1,Fev,2059,681,28,False,4107,NaN
2,Mar,1837,656,31,False,5944,1981.333333
3,Abr,1484,433,30,False,7428,1793.333333
4,Mai,1535,574,31,False,8963,1618.666667
5,Jun,1654,578,30,False,10617,1557.666667
6,Jul,2083,637,31,False,12700,1757.333333
7,Ago,2584,888,31,True,15284,2107.000000

Para calcular apenas a média da coluna 'Entradas_GEREL', as linhas essenciais seriam:

In [5]:
import pandas as pd

# 1. Criação do DataFrame base simulando os meses da operação (se 'dados' já estiver definido, esta parte não é necessária)
dados = {
    'Mes': ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago'],
    'Entradas_GEREL': [2048, 2059, 1837, 1484, 1535, 1654, 2083, 2584],
    'Escalonados_GECRE': [589, 681, 656, 433, 574, 578, 637, 888],
    'Dias_Corridos': [31, 28, 31, 30, 31, 30, 31, 31]
}

df = pd.DataFrame(dados)

# Calcula a média
media_entradas = df['Entradas_GEREL'].mean()

# Imprime a média
print(f"Média das Entradas_GEREL: {media_entradas}")

Média das Entradas_GEREL: 1910.5

No seu código anterior:

*   `df = pd.DataFrame(dados)`: Esta linha é essencial para transformar o dicionário `dados` em um DataFrame do pandas, permitindo que você trabalhe com ele como uma tabela.
*   `media = df['Entradas_GEREL'].mean()`: Esta é a linha que realmente calcula a média da coluna 'Entradas_GEREL'.
*   `mediana = df['Entradas_GEREL'].median()` e `desvio_padrao = df['Entradas_GEREL'].std()`: Essas linhas calculam a mediana e o desvio padrão, respectivamente. Elas não são necessárias se você só precisa da média.
*   `print(f"Média: {media}")`: Esta linha é para exibir o valor da média no console.